apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-test-app
spec:
  replicas: 2  # Number of pods
  selector:
    matchLabels:
      app: kubernetes-test-app
  template:
    metadata:
      labels:
        app: kubernetes-test-app
    spec:
      containers:
      - name: kubernetes-test-app
        image: kubernetes-test-app:latest
        imagePullPolicy: Never  # Tell Kubernetes not to pull from a remote registry
        # image: ayanarshad02/kubernetes-test-app:latest # remote repo image
        resources:
          limits:
            memory: "64Mi"
            cpu: "200m"
        ports:
        - containerPort: 5000
---
# service file, we need to create service file to expose the deployment
# we can also create service.yaml file and write the below content in that file
# or we can write here itself by just using --- at the end of deployment.yaml file

# service.yaml is used to expose the deployment
apiVersion: v1
kind: Service
metadata:
  name: kubernetes-test-app
spec:
  selector:
    app: kubernetes-test-app
  ports:
  - port: 8080
    targetPort: 5000

# Note:
# By default imagePullPolicy is enabled and it searches for image from remote registry,
# so we need to specify imagePullPolicy: Never [line 18] if we want to use local image and
# don't want it to search image in remote registry such as dockerhub
# and
# if we want to pull image from remote registry then
# we need to comment out line 17 and 18 and uncomment line 19
